# Permalinks
permalink:            /:categories/:title/

# Setup
title:                "MOONLIGHT"
tagline:              "The dark side of STARLIGHT."
url:                  "https://resir014.github.io" # the base hostname & protocol for your site
baseurl:              "/moonlight-radio" # the subpath of your site, e.g. "/blog"
exclude:              ["Makefile", "Gruntfile.js", "Gemfile", "README", "LICENSE", "tasks", "node_modules", "package.json"]
keep_files:           ["share", "uploads", "bot", ".htaccess"] # keep a bunch of folders intact, including ATLAS's bot

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:           _sass
  style:              :compressed

# Site authors
author:
  name:               "the MOONLIGHT crew"

# List of time zones supported in the TZ database
# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:             UTC

# Jekyll plugins
gems:
  - jekyll-sitemap
  - jekyll-paginate-v2

# octopress-paginate
pagination:
  enabled: true
  limit:              0
  per_page:           1
  permalink:          /page/:num/

# Navigational menus
nav:
  - title: Home
    url: /index.html
  - title: Logs
    url: /logs
  - title: Files
    url: /files

collections:
  stuff:
    output:           true
    permalink:        /:path/
  archived-logs:
    output:           true
    permalink:        /:collection/:path/
  hidden_posts:
    output:           true
    permalink:        /:collection/:path/ #can be overriden in the file
